language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

before_script:
    # Update Composer
    - travis_retry composer self-update

    # Install Nette Tester
    - travis_retry composer install --no-interaction --prefer-source

    # Setup database
    - mysql -e 'CREATE DATABASE yetorm_test;'

    # Coveralls
    - travis_retry [ ! -e "./tests/php.ini" ] && touch ./tests/php.ini
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cat ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini >> ./tests/php.ini; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then NTESTER_FLAGS="--coverage ./coverage.xml --coverage-src ./src"; else TESTER_FLAGS=""; fi

script:
    - vendor/bin/tester tests -s -p php -c tests/php.ini $NTESTER_FLAGS

after_script:
    # Coveralls
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then composer require satooshi/php-coveralls; fi
    - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then php vendor/bin/coveralls -c tests/.coveralls.yml -v; fi

after_failure:
    # Print *.actual content
    - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
    directories:
        - $HOME/.composer/cache
